---
# tasks file for ansible-tfswitch

- name: Create tfswitch directory
  file: path=/opt/tfswitch state=directory mode="a+rw"

- name: Get tfswitch
  get_url:
    url: https://github.com/warrensbox/terraform-switcher/releases/download/{{ tfswitch_version }}/terraform-switcher_{{ tfswitch_version }}_linux_amd64.tar.gz
    dest: "/opt/tfswitch/terraform-switcher_linux_amd64.tar.gz"
    mode: 0755

- name: Verify tfswitch exists
  stat: path=/opt/tfswitch/tfswitch
  register: tfswitch_stat

- name: Unarchive tfswitch
  unarchive:
    src: /opt/tfswitch/terraform-switcher_linux_amd64.tar.gz
    dest: /opt/tfswitch/
    remote_src: yes

- name: Configure tfswitch on system bin.
  file:
    src: "/opt/tfswitch/tfswitch"
    dest: "/usr/bin/tfswitch"
    state: link
  when: tfswitch_stat.stat.exists

- name: Configure tfswitch on system sbin.
  file:
    src: "/opt/tfswitch/tfswitch"
    dest: "/usr/sbin/tfswitch"
    state: link
  when: tfswitch_stat.stat.exists

- command: tfswitch -v
  register: result_tfswitch
  failed_when: false
  changed_when: false

- debug:
    var: result_tfswitch.stdout